import { motion } from "framer-motion";
import { Sparkles, ChevronDown, ChevronUp } from "lucide-react";
import { useState } from "react";

const planData = [
  {
    week: "Week 1 · Stabilization",
    status: "Current",
    aiAdjusted: true,
    days: [
      {
        day: "Day 1",
        date: "Mon",
        primary: "Reduce cigarettes to 8 per day",
        emotional: "5-minute grounding journal",
        body: "Drink 2L of water and 10-minute walk",
      },
      {
        day: "Day 2",
        date: "Tue",
        primary: "Swap morning cigarette with breathing ritual",
        emotional: "Gratitude text to accountability partner",
        body: "Light stretches + protein breakfast",
      },
    ],
  },
  {
    week: "Week 2 · Reduction",
    status: "Upcoming",
    aiAdjusted: false,
    days: [
      {
        day: "Day 8",
        date: "Mon",
        primary: "Cigarettes down to 6 per day",
        emotional: "Evening reflection: highlight wins",
        body: "Walk after dinner instead of scrolling",
      },
    ],
  },
  {
    week: "Week 3 · Deep Healing",
    status: "Upcoming",
    aiAdjusted: true,
    days: [
      {
        day: "Day 15",
        date: "Mon",
        primary: "Introduce nicotine-free mornings",
        emotional: "Cognitive reframing exercise",
        body: "30-minute dopamine detox walk",
      },
    ],
  },
];

export default function RecoveryPlan() {
  const [expanded, setExpanded] = useState<string>("Week 1 · Stabilization");

  return (
    <div className="space-y-8 p-4 md:p-8">
      <header className="rounded-3xl border border-teal-100 bg-gradient-to-br from-teal-50 via-white to-blue-50 p-6 shadow-sm">
        <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
          <div>
            <p className="text-sm uppercase tracking-[0.4em] text-teal-500">Your scientific recovery plan</p>
            <h1 className="mt-3 text-3xl font-semibold text-slate-900">Generated by Ria — adapts with your progress</h1>
            <p className="mt-2 text-slate-600">
              Ria watches triggers, mood, and task completion to adjust every phase before you need it.
            </p>
          </div>
          <div className="rounded-2xl border border-white/60 bg-white px-5 py-4 shadow-lg">
            <p className="text-sm text-slate-500">Current phase</p>
            <p className="text-2xl font-semibold text-slate-900">Week 2 · Day 3</p>
            <p className="text-xs text-slate-400">62% of milestone complete</p>
          </div>
        </div>
      </header>

      <div className="relative pl-4">
        <span className="absolute left-8 top-0 h-full w-1 rounded-full bg-gradient-to-b from-teal-300 to-blue-400" />
        <div className="space-y-6">
          {planData.map((section) => {
            const isOpen = expanded === section.week;
            return (
              <motion.div
                key={section.week}
                className="relative rounded-3xl border border-slate-100 bg-white/80 p-6 shadow-lg backdrop-blur"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
              >
                <div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between">
                  <div>
                    <div className="flex items-center gap-3">
                      <h2 className="text-2xl font-semibold text-slate-900">{section.week}</h2>
                      {section.aiAdjusted && (
                        <span className="inline-flex items-center gap-1 rounded-full bg-gradient-to-r from-teal-100 to-blue-100 px-3 py-1 text-xs font-semibold text-teal-700">
                          <Sparkles size={14} /> AI adjusted
                        </span>
                      )}
                    </div>
                    <p className="text-sm text-slate-500">{section.status}</p>
                  </div>
                  <button
                    onClick={() => setExpanded(isOpen ? "" : section.week)}
                    className="flex items-center gap-2 rounded-full border border-slate-200 px-4 py-2 text-sm font-semibold text-slate-600"
                  >
                    {isOpen ? "Hide days" : "Show days"}
                    {isOpen ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                  </button>
                </div>

                {isOpen && (
                  <motion.div initial={{ height: 0 }} animate={{ height: "auto" }} className="mt-6 space-y-4">
                    {section.days.map((day) => (
                      <div key={day.day} className="rounded-2xl border border-slate-100 bg-white/80 p-5 shadow-inner">
                        <div className="flex flex-wrap items-center gap-3">
                          <p className="text-sm font-semibold uppercase tracking-[0.4em] text-teal-500">
                            {day.day} · {day.date}
                          </p>
                          <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
                            Rhythm · Stabilize
                          </span>
                        </div>
                        <div className="mt-4 grid gap-4 md:grid-cols-3">
                          <div className="rounded-2xl bg-gradient-to-br from-teal-50 to-white p-4">
                            <p className="text-xs font-semibold uppercase tracking-[0.4em] text-teal-500">🎯 Primary task</p>
                            <p className="mt-2 text-sm text-slate-700">{day.primary}</p>
                          </div>
                          <div className="rounded-2xl bg-gradient-to-br from-blue-50 to-white p-4">
                            <p className="text-xs font-semibold uppercase tracking-[0.4em] text-blue-500">🧘 Emotional</p>
                            <p className="mt-2 text-sm text-slate-700">{day.emotional}</p>
                          </div>
                          <div className="rounded-2xl bg-gradient-to-br from-emerald-50 to-white p-4">
                            <p className="text-xs font-semibold uppercase tracking-[0.4em] text-emerald-500">💪 Body</p>
                            <p className="mt-2 text-sm text-slate-700">{day.body}</p>
                          </div>
                        </div>
                      </div>
                    ))}
                  </motion.div>
                )}
              </motion.div>
            );
          })}
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        <div className="rounded-3xl border border-slate-100 bg-white/80 p-6 shadow-lg backdrop-blur">
          <h3 className="text-lg font-semibold text-slate-900">Why this plan?</h3>
          <p className="mt-3 text-sm text-slate-600">
            Ria layers CBT rituals, motivational interviewing prompts, and body-based resets. Each phase focuses on a different
            nervous system state so cravings feel lighter, not like a battle.
          </p>
        </div>
        <div className="rounded-3xl border border-slate-100 bg-white/80 p-6 shadow-lg backdrop-blur">
          <h3 className="text-lg font-semibold text-slate-900">Need adjustments?</h3>
          <p className="mt-3 text-sm text-slate-600">Tap below and Ria will rewrite the plan in real time.</p>
          <button className="mt-4 rounded-full border border-teal-200 px-5 py-3 text-sm font-semibold text-teal-600">
            Chat with Ria
          </button>
        </div>
      </div>
    </div>
  );
}

